services:
  - type: web
    name: luma-scraper-clean
    runtime: docker
    repo: https://github.com/ShonZimkov/luma-scraper-clean
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: API_KEY
        sync: false